language: php
php:
    - 7.2
services:
    - docker
before_script:
    - composer install
    - docker build . -t test_identity
script: docker run -it --rm -v "$PWD":/usr/src/lib test_identity
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
