arguments:
    metas: array
    neo4jPassword: string

dependencies:
    transport @innmind/http-transport/container.yml: []

    dbal @innmind/neo4j-dbal/container.yml:
        transport: $transport.thrower
        clock: $infrastructure.clock
        password: $neo4jPassword
        scheme: http

    neo4j @innmind/neo4j-onm/container.yml:
        connection: $dbal.connection
        metas: $metas
        extractionStrategy: $infrastructure.neo4j.reflection.extraction
        injectionStrategy: $infrastructure.neo4j.reflection.injection
        instanciator: $infrastructure.neo4j.reflection.instanciator
        additionalTypes: $infrastructure.neo4j.additionalTypes
        additionalGenerators: $infrastructure.neo4j.additionalGenerators

    commandBus @innmind/command-bus/container.yml:
        handlers: $handlers

    eventBus @innmind/event-bus/container.yml:
        listeners: $listeners

expose:
    commands: $commands

services:
    commands Innmind\CLI\Commands:
        - $component.identity.command.create

    appCommandBus stack:
        - $commandBus.queue
        - $appCommandBus.transaction
        - $appCommandBus.clearDomainEvents
        - $appCommandBus.dispatchDomainEvents
        - $appCommandBus.flush
        - $commandBus.bus

    appCommandBus:
        clearDomainEvents Innmind\Neo4j\ONM\CommandBus\ClearDomainEvents:
            - '@decorated'
            - $neo4j.container

        dispatchDomainEvents Innmind\Neo4j\ONM\CommandBus\DispatchDomainEvents:
            - '@decorated'
            - $eventBus.bus
            - $neo4j.container

        flush Innmind\Neo4j\ONM\CommandBus\Flush:
            - '@decorated'
            - $neo4j.manager

        transaction Innmind\Neo4j\ONM\CommandBus\Transaction:
            - '@decorated'
            - $neo4j.manager

    handlers merge:
        - $component.identity.handlers
        - $component.calendar.handlers

    listeners merge:
        - $component.identity.listeners
        - $component.calendar.listeners

    infrastructure:
        clock Innmind\TimeContinuum\TimeContinuum\Earth:
            - $infrastructure.clock.timezone

        clock:
            timezone Innmind\TimeContinuum\Timezone\Earth\UTC: []

        neo4j:
            reflection:
                extraction Innmind\Reflection\ExtractionStrategy\ReflectionStrategy: []
                injection Innmind\Reflection\InjectionStrategy\ReflectionStrategy: []
                instanciator Innmind\Reflection\Instanciator\ConstructorLessInstanciator: []

            types set<string>:
                - Innmind\Neo4j\ONM\Type\PointInTimeType

            additionalTypes merge:
                - $component.identity.additionalTypes
                - $component.calendar.additionalTypes
                - $component.files.additionalTypes
                - $infrastructure.neo4j.types

            additionalGenerators merge:
                - $component.identity.additionalGenerators
                - $component.calendar.additionalGenerators

    component:
        identity:
            command:
                create PersonalGalaxy\X\Command\Identity\Create:
                    - $appCommandBus
                    - $neo4j.manager
                    - $component.identity.listener.recoveryCodes

            handlers map<string, callable>:
                - <PersonalGalaxy\Identity\Command\CreateIdentity, $component.identity.handler.createIdentity>
                - <PersonalGalaxy\Identity\Command\DeleteIdentity, $component.identity.handler.deleteIdentity>
                - <PersonalGalaxy\Identity\Command\Identity\ChangePassword, $component.identity.handler.changePassword>
                - <PersonalGalaxy\Identity\Command\Identity\Disable2FA, $component.identity.handler.disable2FA>
                - <PersonalGalaxy\Identity\Command\Identity\Enable2FA, $component.identity.handler.enable2FA>
                - <PersonalGalaxy\Identity\Command\Identity\Validate2FACode, $component.identity.handler.validate2FACode>
                - <PersonalGalaxy\Identity\Command\Identity\VerifyPassword, $component.identity.handler.verifyPassword>

            handler:
                createIdentity PersonalGalaxy\Identity\Handler\CreateIdentityHandler:
                    - $component.identity.repository
                deleteIdentity PersonalGalaxy\Identity\Handler\DeleteIdentityHandler:
                    - $component.identity.repository
                changePassword PersonalGalaxy\Identity\Handler\Identity\ChangePasswordHandler:
                    - $component.identity.repository
                disable2FA PersonalGalaxy\Identity\Handler\Identity\Disable2FAHandler:
                    - $component.identity.repository
                enable2FA PersonalGalaxy\Identity\Handler\Identity\Enable2FAHandler:
                    - $component.identity.repository
                validate2FACode PersonalGalaxy\Identity\Handler\Identity\Validate2FACodeHandler:
                    - $component.identity.repository
                verifyPassword PersonalGalaxy\Identity\Handler\Identity\VerifyPasswordHandler:
                    - $component.identity.repository

            listeners map<string, Innmind\Immutable\SetInterface>:
                - <PersonalGalaxy\Identity\Event\Identity\TwoFactorAuthenticationWasEnabled, $component.identity.listeners.recoveryCodes>

            listeners:
                recoveryCodes set<callable>:
                    - $component.identity.listener.recoveryCodes

            listener:
                recoveryCodes PersonalGalaxy\X\Component\Identity\Listener\RecoveryCodes: []

            repository PersonalGalaxy\X\Repository::build:
                - $neo4j.manager
                - PersonalGalaxy\X\Component\Identity\Repository\IdentityRepository
                - PersonalGalaxy\Identity\Entity\Identity

            additionalTypes set<string>:
                - PersonalGalaxy\X\Component\Identity\Type\EmailType
                - PersonalGalaxy\X\Component\Identity\Type\PasswordType
                - PersonalGalaxy\X\Component\Identity\Type\RecoveryCodeType
                - PersonalGalaxy\X\Component\Identity\Type\SecretKeyType

            additionalGenerators map<string, Innmind\Neo4j\ONM\Identity\Generator>:
                - <PersonalGalaxy\X\Component\Identity\Entity\Identity, $component.identity.generator.identity>

            generator:
                identity Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                    - PersonalGalaxy\X\Component\Identity\Entity\Identity

        calendar:
            handlers map<string, callable>:
                - <PersonalGalaxy\Calendar\Command\AddAgenda, $component.calendar.handler.agenda.add>
                - <PersonalGalaxy\Calendar\Command\DeleteAgenda, $component.calendar.handler.agenda.wrap.delete>
                - <PersonalGalaxy\Calendar\Command\RenameAgenda, $component.calendar.handler.agenda.rename>
                - <PersonalGalaxy\Calendar\Command\AddEvent, $component.calendar.handler.event.add>
                - <PersonalGalaxy\Calendar\Command\CancelEvent, $component.calendar.handler.event.cancel>
                - <PersonalGalaxy\Calendar\Command\MoveEvent, $component.calendar.handler.event.move>
                - <PersonalGalaxy\Calendar\Command\RenameEvent, $component.calendar.handler.event.rename>
                - <PersonalGalaxy\Calendar\Command\Event\AddNote, $component.calendar.handler.event.addNote>

            handler:
                agenda:
                    add PersonalGalaxy\Calendar\Handler\AddAgendaHandler:
                        - $component.calendar.repository.agenda
                    delete PersonalGalaxy\Calendar\Handler\DeleteAgendaHandler:
                        - $component.calendar.repository.agenda
                        - $component.calendar.repository.event
                        - $component.calendar.handler.event.cancel
                    rename PersonalGalaxy\Calendar\Handler\RenameAgendaHandler:
                        - $component.calendar.repository.agenda
                    wrap:
                        delete PersonalGalaxy\X\Component\Calendar\Handler\DeleteAgendaHandler:
                            - $component.calendar.handler.agenda.delete
                            - $dbal.connection
                event:
                    add PersonalGalaxy\Calendar\Handler\AddEventHandler:
                        - $component.calendar.repository.event
                        - $component.calendar.repository.agenda
                        - $infrastructure.clock
                    cancel PersonalGalaxy\Calendar\Handler\CancelEventHandler:
                        - $component.calendar.repository.event
                    move PersonalGalaxy\Calendar\Handler\MoveEventHandler:
                        - $component.calendar.repository.event
                        - $infrastructure.clock
                    rename PersonalGalaxy\Calendar\Handler\RenameEventHandler:
                        - $component.calendar.repository.event
                    addNote PersonalGalaxy\Calendar\Handler\Event\AddNoteHandler:
                        - $component.calendar.repository.event

            repository:
                agenda PersonalGalaxy\X\Repository::build:
                    - $neo4j.manager
                    - PersonalGalaxy\X\Component\Calendar\Repository\AgendaRepository
                    - PersonalGalaxy\Calendar\Entity\Agenda

                event PersonalGalaxy\X\Repository::build:
                    - $neo4j.manager
                    - PersonalGalaxy\X\Component\Calendar\Repository\EventRepository
                    - PersonalGalaxy\Calendar\Entity\Event

            listeners map<string, Innmind\Immutable\SetInterface>:
                - <PersonalGalaxy\Calendar\Event\AgendaWasAdded, $component.calendar.listeners.agendaWasAdded>

            listeners:
                agendaWasAdded set<callable>:
                    - $component.calendar.listener.bindAgendaToIdentity

            listener:
                bindAgendaToIdentity PersonalGalaxy\X\Component\Calendar\Listener\BindAgendaToIdentity:
                    - $dbal.connection

            additionalTypes set<string>:
                - PersonalGalaxy\X\Component\Calendar\Type\Agenda\NameType
                - PersonalGalaxy\X\Component\Calendar\Type\Agenda\UserType
                - PersonalGalaxy\X\Component\Calendar\Type\Event\AgendaType
                - PersonalGalaxy\X\Component\Calendar\Type\Event\NameType
                - PersonalGalaxy\X\Component\Calendar\Type\Event\NoteType
                - PersonalGalaxy\X\Component\Calendar\Type\Event\SlotType

            additionalGenerators map<string, Innmind\Neo4j\ONM\Identity\Generator>:
                - <PersonalGalaxy\X\Component\Calendar\Entity\Agenda, $component.calendar.generator.agenda>
                - <PersonalGalaxy\X\Component\Calendar\Entity\Event, $component.calendar.generator.event>

            generator:
                agenda Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                    - PersonalGalaxy\X\Component\Calendar\Entity\Agenda
                event Innmind\Neo4j\ONM\Identity\Generator\UuidGenerator:
                    - PersonalGalaxy\X\Component\Calendar\Entity\Event

        files:
            additionalTypes set<string>:
                - PersonalGalaxy\X\Component\Files\Type\Folder\NameType
                - PersonalGalaxy\X\Component\Files\Type\Folder\IdentityType
                - PersonalGalaxy\X\Component\Files\Type\File\NameType
                - PersonalGalaxy\X\Component\Files\Type\File\MediaTypeType
